### ISSUE TITLE
No implementation found for method sendToBackground

### ISSUE THREAD

**Issue by tsepulvedacaroca01** [ppicas/flutter-android-background#2]
Hello, I am new to flutter and I am quite interested in this functionality, I have managed to implement that the application is not closed at the time of minimizing (home button and changing window) but at the moment of pressing the “back” button it does not minimize the application and throws me this error. Any ideas?

```
E/flutter ( 8879): [ERROR:flutter/lib/ui/ui_dart_state.cc(157)] Unhandled Exception: MissingPluginException(No implementation found for method sendToBackground on channel com.example/app_retain)
E/flutter ( 8879): #0      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:319:7)
E/flutter ( 8879): <asynchronous suspension>
E/flutter ( 8879): #1      AppRetainWidget.build.<anonymous closure> (package:gms/background_app/app_retain_widget.dart:21:22)
E/flutter ( 8879): #2      ModalRoute.willPop (package:flutter/src/widgets/routes.dart:1135:26)
E/flutter ( 8879): #3      NavigatorState.maybePop (package:flutter/src/widgets/navigator.dart:2078:57)
E/flutter ( 8879): #4      _WidgetsAppState.didPopRoute (package:flutter/src/widgets/app.dart:807:28)
E/flutter ( 8879): #5      WidgetsBinding.handlePopRoute (package:flutter/src/widgets/binding.dart:506:26)
E/flutter ( 8879): #6      WidgetsBinding._handleNavigationInvocation (package:flutter/src/widgets/binding.dart:534:16)
E/flutter ( 8879): #7      MethodChannel._handleAsMethodCall (package:flutter/src/services/platform_channel.dart:402:55)
E/flutter ( 8879): #8      MethodChannel.setMethodCallHandler.<anonymous closure> (package:flutter/src/services/platform_channel.dart:370:54)
E/flutter ( 8879): #9      _DefaultBinaryMessenger.handlePlatformMessage (package:flutter/src/services/binding.dart:200:33)
E/flutter ( 8879): #10     _invoke3.<anonymous closure> (dart:ui/hooks.dart:303:15)
E/flutter ( 8879): #11     _rootRun (dart:async/zone.dart:1126:13)
E/flutter ( 8879): #12     _CustomZone.run (dart:async/zone.dart:1023:19)
E/flutter ( 8879): #13     _CustomZone.runGuarded (dart:async/zone.dart:925:7)
E/flutter ( 8879): #14     _invoke3 (dart:ui/hooks.dart:302:10)
E/flutter ( 8879): #15     _dispatchPlatformMessage (dart:ui/hooks.dart:162:5)
```

**Comment by ppicas** [comment]
Hi @tsepulvedacaroca01, I think that the cause of your problem might be that you don't have registered the `MethodChannel` in android side.

Please check this code: https://github.com/ppicas/flutter-android-background/blob/b6d025a9005daa816a30ca981f255876779f97be/android/app/src/main/kotlin/com/example/background/MainActivity.kt#L27
